=== jdds97/Repositorio-VSCode/EJERCICIOS DTD/ligaFutbol.dtd
<!ELEMENT ligaFutbol (partidos)*>
<!ELEMENT partidos (equipoLocal,equipoVisitante)>
<!ELEMENT equipoLocal EMPTY>
<!ATTLIST equipoLocal goles NMTOKEN #REQUIRED>
<!ATTLIST equipoLocal nombre CDATA #REQUIRED>
<!ELEMENT equipoVisitante EMPTY>
<!ATTLIST equipoVisitante goles NMTOKEN #REQUIRED>
<!ATTLIST equipoVisitante nombre CDATA #REQUIRED>

=== jdds97/Repositorio-VSCode/LIGA-FUTBOL.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE ligaFutbol SYSTEM "ligaFutbol.dtd">
<ligaFutbol>
    <partidos>
        <equipoLocal goles="10" nombre="Sevilla"/>
        <equipoVisitante goles="8" nombre="Betis"/>
    </partidos>
    <partidos>
        <equipoLocal goles="2" nombre="Madrid"/>
        <equipoVisitante goles="3" nombre="Sevilla"/>
    </partidos>
    <equipoLocal goles="1" nombre="Atleti"/>
    <equipoVisitante goles="2" nombre="Alaves"/>
</ligaFutbol>
