=== jdds97/Repositorio-VSCode/EJERCICIOS DTD/recetas.dtd
<!ELEMENT recetas (receta*)>
<!ELEMENT receta (nombre, ingrediente+,instrucciones) >
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT ingrediente (#PCDATA)>
<!ELEMENT instrucciones (#PCDATA)>
<!ATTLIST receta
    numeroRaciones CDATA #REQUIRED
    dificultad (baja|media|alta) CDATA  "media"#IMPLIED >
<!ATTLIST ingrediente
    cantidad CDATA #REQUIRED
    unidad CDATA #REQUIRED>

=== jdds97/Repositorio-VSCode/EJERCICIOS DTD/receta-cocina.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE recetas SYSTEM "recetas.dtd">
<recetas>
    <receta numeroRaciones="2" dificultad="alta">
        <nombre> Pollo a la carbonara</nombre>
        <ingrediente cantidad="1" unidad="kg">Pollo</ingrediente>
        <ingrediente cantidad="100" unidad="ml" >Salsa carbonara</ingrediente>
        <instrucciones>
            Descongelar el pollo y llevarlo al horno a 180ª durante 40 min
        </instrucciones>
    </receta>
    <receta numeroRaciones="3" dificultad="baja">
        <nombre> Arroz con bogavante</nombre>
        <ingrediente>Arroz </ingrediente>
        <instrucciones>
            Prepara el arroz
        </instrucciones>
    </receta>
</recetas>
